version: "3.7"

services:
  backend:
    build: ./back
    volumes:
      - ./back:/home/node/app
    ports:
      - 3000:3000

  frontend:
    build: ./front
    volumes:
      - ./front:/home/node/app
    ports:
      - 3001:3000
    depends_on:
      - backend
